"""Validate and retire physical projections generated by old Journals."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any


def verify_legacy_projections(journals: list[Path]) -> None:
    """Refuse deletion unless every legacy carrier is carried by its Journal."""
    for journal in journals:
        expected = journal_sections(journal)
        sections = journal.parent / "sections"
        if not sections.is_dir():
            continue
        for path in sections.glob("*.json"):
            value = read_json(path)
            if is_legacy_section_carrier(value) and section_key(
                value["checkpoint_ref"], value["sections"]
            ) not in expected:
                raise ValueError(
                    "legacy section projection does not match JOURNAL source: "
                    + str(path)
                )


def retire_verified_section_carriers(branch: Path) -> None:
    sections = branch / "sections"
    if not sections.is_dir():
        return
    for path in sections.glob("*.json"):
        if is_legacy_section_carrier(read_json(path)):
            path.unlink()
    try:
        sections.rmdir()
    except OSError:
        pass


def journal_sections(journal: Path) -> set[str]:
    value = read_json(journal)
    checkpoints = value.get("checkpoints") if isinstance(value, dict) else None
    if not isinstance(checkpoints, list):
        raise ValueError("old JOURNAL has no checkpoints")
    result: set[str] = set()
    for checkpoint in checkpoints:
        if not isinstance(checkpoint, dict):
            raise ValueError("old JOURNAL checkpoint is invalid")
        ref, sections = checkpoint.get("checkpoint_ref"), checkpoint.get("sections")
        if not isinstance(ref, str) or not ref or not isinstance(sections, list):
            raise ValueError("old JOURNAL checkpoint is invalid")
        result.add(section_key(ref, sections))
    return result


def is_legacy_section_carrier(value: Any) -> bool:
    return (
        isinstance(value, dict) and value.get("schema_version") in {2, 3}
        and isinstance(value.get("checkpoint_ref"), str)
        and isinstance(value.get("sections"), list)
        and isinstance(value.get("section_hash"), str)
    )


def section_key(checkpoint_ref: str, sections: list[Any]) -> str:
    return json.dumps(
        {"checkpoint_ref": checkpoint_ref, "sections": sections},
        ensure_ascii=False, sort_keys=True, separators=(",", ":"),
    )


def read_json(path: Path) -> Any:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ValueError(f"cannot read retired report projection: {path}") from exc
