"""Unified FieldHistory audit entrypoint.

There are two supported audit modes:

``2024-plus``
    Checks that every listed futures product has replayable historical-field
    state from the 2024 boundary onward.  This mode accepts
    ``asof_confirmed`` rows as temporary coverage anchors.

``full-history``
    Checks the source-of-truth history from true baselines and dated changes.
    Settlement-parameter snapshots are not ingested as history.  Instead,
    provide a JSONL file generated by
    ``fetch_transaction_fee_settlement_snapshots.py --mode changes``; this
    audit verifies that snapshot changes are covered by ingested
    notice/listing/rule events.
"""

from __future__ import annotations

import argparse
import json
from collections import Counter
from pathlib import Path

from sources.FieldHistory.scripts import audit_2024_field_history_coverage
from sources.FieldHistory.scripts.audit_field_history_event_chain import (
    audit_event_chain,
    write_event_chain_csv,
)
from sources.FieldHistory.scripts import audit_transaction_fee_settlement_snapshot_alignment


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--mode", choices=("2024-plus", "full-history"), required=True)
    parser.add_argument("--store-key", default="openctp")
    parser.add_argument("--db", default=audit_2024_field_history_coverage.DEFAULT_DB)
    parser.add_argument("--asof-day", default=audit_2024_field_history_coverage.DEFAULT_ASOF_DAY)
    parser.add_argument("--output-csv", required=True)
    parser.add_argument("--limit", type=int, default=80)
    parser.add_argument(
        "--settlement-snapshot-jsonl",
        default="",
        help=(
            "Required for --mode full-history. JSONL generated by "
            "fetch_transaction_fee_settlement_snapshots.py --mode changes."
        ),
    )
    parser.add_argument(
        "--also-run-2024-plus",
        action="store_true",
        help="In full-history mode, also write a sibling .2024-plus.csv coverage audit.",
    )
    parser.add_argument(
        "--event-chain-csv",
        default="",
        help=(
            "Optional CSV path for event-chain quality issues. In full-history "
            "mode this defaults to a sibling .event-chain.csv report."
        ),
    )
    args = parser.parse_args(argv)

    if args.mode == "2024-plus":
        return audit_2024_field_history_coverage.main([
            "--db",
            args.db,
            "--store-key",
            args.store_key,
            "--asof-day",
            args.asof_day,
            "--output-csv",
            args.output_csv,
            "--limit",
            str(args.limit),
        ])

    if not args.settlement_snapshot_jsonl:
        raise ValueError("--settlement-snapshot-jsonl is required for --mode full-history")
    result = audit_transaction_fee_settlement_snapshot_alignment.main([
        args.settlement_snapshot_jsonl,
        "--store-key",
        args.store_key,
        "--output-csv",
        args.output_csv,
        "--require-change-mode",
    ])
    event_chain_rows = audit_event_chain(store_key=args.store_key, asof_day=None)
    event_chain_csv = args.event_chain_csv or args.output_csv.removesuffix(".csv") + ".event-chain.csv"
    write_event_chain_csv(Path(event_chain_csv).expanduser(), event_chain_rows)
    print(json.dumps({
        "event_chain_rows": len(event_chain_rows),
        "event_chain_output": str(Path(event_chain_csv).expanduser().resolve()),
        "event_chain_status_counts": Counter(row["status"] for row in event_chain_rows),
    }, ensure_ascii=False, indent=2, default=dict))
    if args.also_run_2024_plus:
        sibling = args.output_csv.removesuffix(".csv") + ".2024-plus.csv"
        audit_2024_field_history_coverage.main([
            "--db",
            args.db,
            "--store-key",
            args.store_key,
            "--asof-day",
            args.asof_day,
            "--output-csv",
            sibling,
            "--limit",
            str(args.limit),
        ])
    return result if result else (2 if event_chain_rows else 0)


if __name__ == "__main__":
    raise SystemExit(main())
