"""Audit official settlement-parameter snapshots against ingested fee events.

Settlement-parameter feeds are official value snapshots, but they are audit
evidence rather than FieldHistory source-of-truth events.  This command reads a
JSONL file generated by ``fetch_transaction_fee_settlement_snapshots.py`` and
checks whether every first-seen/value-change snapshot row is covered by an
ingested exchange notice/listing/rule event in SQLite.

It is intentionally read-only: it does not append agent events, materialize
history rows, or rebuild views.
"""

from __future__ import annotations

import argparse
import csv
import json
import sqlite3
from collections import Counter
from pathlib import Path
from typing import Any

from sources.FieldHistory.scripts.audit_transaction_fee_announcement_alignment import (
    FEE_FIELDS,
    _active_fee_unit_field_before,
    _companion_fee_unit_field,
    _contract_scope_covers,
    _find_notice,
    _snapshot_index,
    _snapshot_key,
)
from tools.data.field_history import _ensure_store_registered
from tools.data.field_history_agent_ingest import AGENT_EVENT_TABLE
from tools.data.hub import DataHub


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("snapshot_jsonl", help="JSONL from fetch_transaction_fee_settlement_snapshots.py --mode changes")
    parser.add_argument("--store-key", default="openctp", help="DataHub SQLite store key")
    parser.add_argument("--output-csv", required=True, help="Audit report CSV path")
    parser.add_argument(
        "--require-change-mode",
        action="store_true",
        help="Fail if the JSONL appears to contain full daily snapshots rather than first-seen/value-change rows.",
    )
    args = parser.parse_args(argv)

    snapshots = _load_snapshot_events(Path(args.snapshot_jsonl).expanduser())
    if args.require_change_mode:
        _assert_probable_change_mode(snapshots)
    notices = _load_ingested_notice_events(store_key=args.store_key)
    snapshot_index = _snapshot_index(snapshots)
    rows = [
        _audit_snapshot(snapshot, notices, snapshot_index=snapshot_index)
        for snapshot in snapshots
    ]
    output = Path(args.output_csv).expanduser().resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=_columns())
        writer.writeheader()
        writer.writerows(rows)
    print(json.dumps({
        "snapshot_rows": len(snapshots),
        "notice_rows": len(notices),
        "output": str(output),
        "status_counts": Counter(row["status"] for row in rows),
        "status_counts_by_exchange": {
            exchange: Counter(row["status"] for row in rows if row["data_source"] == exchange)
            for exchange in sorted({row["data_source"] for row in rows})
        },
    }, ensure_ascii=False, indent=2, default=dict))
    return 0 if not any(row["status"].startswith("missing_") for row in rows) else 2


def _load_snapshot_events(path: Path) -> list[dict[str, Any]]:
    events: list[dict[str, Any]] = []
    with path.resolve().open("r", encoding="utf-8") as handle:
        for line_number, line in enumerate(handle, start=1):
            text = line.strip()
            if not text or text.startswith("#"):
                continue
            row = json.loads(text)
            if row.get("field_group") != "TransactionFee":
                continue
            if row.get("field_name") not in FEE_FIELDS:
                continue
            if "settlement-parameters-" not in str(row.get("source_notice_id") or ""):
                raise ValueError(f"{path}:{line_number}: snapshot row must use settlement-parameters source_notice_id")
            events.append(row)
    return events


def _assert_probable_change_mode(snapshots: list[dict[str, Any]]) -> None:
    """Guard against accidentally auditing every daily snapshot as a change."""
    by_source_day: Counter[tuple[str, str]] = Counter(
        (str(row.get("data_source") or ""), str(row.get("effective_trading_day") or ""))
        for row in snapshots
    )
    dense_days = [key for key, count in by_source_day.items() if count > 500]
    if len(dense_days) > 30:
        raise ValueError(
            "snapshot_jsonl looks like full daily snapshots, not --mode changes output; "
            f"dense source/day groups={len(dense_days)}"
        )


def _load_ingested_notice_events(*, store_key: str) -> list[dict[str, Any]]:
    hub = DataHub.get_instance()
    _ensure_store_registered(hub, store_key)
    with hub.connect_store(store_key) as conn:
        conn.row_factory = sqlite3.Row
        rows = conn.execute(
            f"""
            SELECT *
            FROM {AGENT_EVENT_TABLE}
            WHERE field_group = 'TransactionFee'
              AND field_name IN ({",".join("?" for _ in FEE_FIELDS)})
              AND COALESCE(source_notice_id, '') NOT LIKE '%settlement-parameters%'
            ORDER BY data_source, instrument, field_name, effective_trading_day, effective_timestamp
            """,
            tuple(sorted(FEE_FIELDS)),
        ).fetchall()
    return [_event_from_agent_row(row) for row in rows]


def _event_from_agent_row(row: sqlite3.Row) -> dict[str, Any]:
    event = dict(row)
    event["value"] = json.loads(event.get("value_json") or "null")
    event["contract_codes"] = json.loads(event.get("contract_codes_json") or "[]")
    event["source_url"] = event.get("source_url") or ""
    event["source_date"] = event.get("source_accessed_at") or ""
    return event


def _audit_snapshot(
    snapshot: dict[str, Any],
    notices: list[dict[str, Any]],
    *,
    snapshot_index: dict[tuple[str, str, str, str, str], dict[str, Any]],
) -> dict[str, str]:
    exact = _find_notice(snapshot, notices, allow_prior=False)
    if exact is not None:
        return _row("aligned_exact_notice", snapshot, exact)
    prior = _find_notice(snapshot, notices, allow_prior=True)
    if prior is not None:
        return _row("aligned_prior_notice", snapshot, prior)
    companion = _unit_companion_notice_match(snapshot, notices, snapshot_index=snapshot_index)
    if companion is not None:
        return _row("aligned_unit_companion", snapshot, companion)
    return _row("missing_notice_for_snapshot_change", snapshot, None)


def _unit_companion_notice_match(
    snapshot: dict[str, Any],
    notices: list[dict[str, Any]],
    *,
    snapshot_index: dict[tuple[str, str, str, str, str], dict[str, Any]],
) -> dict[str, Any] | None:
    try:
        value = float(snapshot.get("value") or 0.0)
    except (TypeError, ValueError):
        return None
    if abs(value) > 1e-15:
        return None
    companion_field = _companion_fee_unit_field(str(snapshot.get("field_name") or ""))
    if not companion_field:
        return None
    companion_snapshot = snapshot_index.get(_snapshot_key(snapshot, companion_field))
    if companion_snapshot is not None:
        exact = _find_notice(companion_snapshot, notices, allow_prior=False)
        if exact is not None:
            return exact
        prior = _find_notice(companion_snapshot, notices, allow_prior=True)
        if prior is not None:
            return prior
    active_field = _active_fee_unit_field_before(snapshot, notices)
    if active_field != companion_field:
        return None
    active_snapshot = {**snapshot, "field_name": active_field}
    return _find_notice(active_snapshot, notices, allow_prior=True)


def _row(status: str, snapshot: dict[str, Any], matched: dict[str, Any] | None) -> dict[str, str]:
    return {
        "status": status,
        "data_source": str(snapshot.get("data_source") or ""),
        "instrument": str(snapshot.get("instrument") or ""),
        "contract_codes": json.dumps(snapshot.get("contract_codes") or [], ensure_ascii=False),
        "field_name": str(snapshot.get("field_name") or ""),
        "effective_trading_day": str(snapshot.get("effective_trading_day") or ""),
        "effective_timestamp": str(snapshot.get("effective_timestamp") or ""),
        "value": str(snapshot.get("value")),
        "snapshot_notice_id": str(snapshot.get("source_notice_id") or ""),
        "snapshot_source_url": str(snapshot.get("source_url") or ""),
        "matched_notice_id": "" if matched is None else str(matched.get("source_notice_id") or ""),
        "matched_notice_day": "" if matched is None else str(matched.get("effective_trading_day") or ""),
        "matched_source_url": "" if matched is None else str(matched.get("source_url") or ""),
    }


def _columns() -> list[str]:
    return [
        "status",
        "data_source",
        "instrument",
        "contract_codes",
        "field_name",
        "effective_trading_day",
        "effective_timestamp",
        "value",
        "snapshot_notice_id",
        "snapshot_source_url",
        "matched_notice_id",
        "matched_notice_day",
        "matched_source_url",
    ]


if __name__ == "__main__":
    raise SystemExit(main())
