"""Fill 2024 boundary CloseToday fee anchors from normal close-fee state.

This script is intentionally narrow.  SHFE/INE settlement parameter feeds do
not expose a normal close-today amount/rate column for every product.  When no
explicit close-today historical row exists at the 2024 boundary, the replayable
fee schema still needs both CloseToday money/volume fields:

* if the sibling CloseToday field already exists, the missing side is the
  inactive zero side;
* if neither CloseToday side exists, close-today uses the normal close fee at
  the boundary.

This does not interpret SHFE/INE TTRADE* hedge fields or ISUNITODAY flags as
normal close-today fees.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
from datetime import datetime
from pathlib import Path
from typing import Any

from sources.FieldHistory.scripts.ingest_field_history_events import _rebuild_view
from tools.data.field_history import (
    HistoricalFieldFallbackPolicy,
    MissingHistoricalField,
    _ensure_store_registered,
    load_historical_field_provider,
)
from tools.data.field_history_agent_ingest import (
    append_agent_field_change_events,
    ensure_agent_event_schema,
    materialize_agent_events_to_history,
)
from tools.data.hub import DataHub


MONEY = "CloseTodayRatioByMoney"
VOLUME = "CloseTodayRatioByVolume"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("audit_csv", help="CSV generated by audit_field_history.py --mode 2024-plus")
    parser.add_argument("--store-key", default="openctp")
    parser.add_argument("--asof-day", default="2024-01-02")
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args(argv)

    events = build_events(Path(args.audit_csv), store_key=args.store_key, asof_day=args.asof_day)
    events = _skip_existing(events, store_key=args.store_key)
    print(json.dumps({
        "candidate_events": len(events),
        "inserted": 0 if args.dry_run else len(events),
        "sample_event_ids": [event["event_id"] for event in events[:20]],
    }, ensure_ascii=False, indent=2))
    if args.dry_run or not events:
        return 0
    append_agent_field_change_events(events, store_key=args.store_key)
    materialize_agent_events_to_history(store_key=args.store_key, field_group="TransactionFee")
    _rebuild_view("TransactionFee", store_key=args.store_key)
    return 0


def build_events(audit_csv: Path, *, store_key: str, asof_day: str) -> list[dict[str, Any]]:
    provider = load_historical_field_provider(store_key=store_key)
    rows = [
        row for row in csv.DictReader(audit_csv.open())
        if row.get("status") == "missing_2024_state"
        and row.get("field_name") in {MONEY, VOLUME}
    ]
    events = []
    accessed_at = datetime.now().astimezone().isoformat(timespec="seconds")
    for row in rows:
        instrument = str(row["instrument"]).upper()
        field_name = str(row["field_name"])
        sibling = VOLUME if field_name == MONEY else MONEY
        close_field = "CloseRatioByMoney" if field_name == MONEY else "CloseRatioByVolume"
        try:
            _resolve(provider, instrument, sibling, asof_day)
        except MissingHistoricalField:
            value = float(_resolve(provider, instrument, close_field, asof_day).value)
            derivation = f"neither close-today side was present; copied {close_field}"
        else:
            value = 0.0
            derivation = f"sibling {sibling} was present; filled inactive side as zero"
        events.append(_event(
            data_source=str(row["exchange"]),
            instrument=instrument,
            label=str(row.get("instrument_label") or instrument),
            field_name=field_name,
            value=value,
            asof_day=asof_day,
            derivation=derivation,
            accessed_at=accessed_at,
        ))
    return events


def _resolve(provider: Any, instrument: str, field_name: str, day: str) -> Any:
    return provider.resolve_by_trading_day(
        instrument,
        field_name,
        day,
        fallback=HistoricalFieldFallbackPolicy.STRICT_HISTORICAL,
    )


def _event(
    *,
    data_source: str,
    instrument: str,
    label: str,
    field_name: str,
    value: float,
    asof_day: str,
    derivation: str,
    accessed_at: str,
) -> dict[str, Any]:
    event_id = "close_today_asof_" + hashlib.sha1(
        f"{data_source}:{instrument}:{field_name}:{asof_day}:{value}".encode("utf-8")
    ).hexdigest()[:24]
    return {
        "event_id": event_id,
        "data_source": data_source,
        "field_group": "TransactionFee",
        "source_url": (
            "https://www.shfe.com.cn/reports/tradedata/dailyandweeklydata/?query_params=js_f"
            if data_source == "SHFE"
            else "https://www.ine.cn/reports/tradedata/dailyandweeklydata/?query_params=js_f"
        ),
        "source_accessed_at": accessed_at,
        "agent_name": f"Agent:{data_source}",
        "requester_key": "field-history-close-today-asof",
        "instrument": instrument,
        "instrument_label": label,
        "instrument_type": "future",
        "scope_type": "product",
        "exchange": {"SHFE": "SHF", "INE": "INE"}.get(data_source, data_source),
        "field_name": field_name,
        "effective_trading_day": asof_day,
        "effective_timestamp": f"{asof_day} 09:00:00",
        "value": value,
        "contract_codes": [],
        "contract_scope_type": "all",
        "change_type": "asof_confirmed",
        "source_notice_id": f"{data_source}-close-today-derived-from-close-fee-{asof_day.replace('-', '')}",
        "raw_note": (
            f"{data_source} settlement parameters confirm the normal close fee at {asof_day}; "
            f"{derivation}. TTRADE hedge fields and ISUNITODAY flags are not used as fee values."
        ),
        "evidence_text": derivation,
        "parser_notes": "Derived schema-completion as-of anchor for CloseToday fee fields.",
    }


def _skip_existing(events: list[dict[str, Any]], *, store_key: str) -> list[dict[str, Any]]:
    if not events:
        return []
    hub = DataHub.get_instance()
    _ensure_store_registered(hub, store_key)
    with hub.connect_store(store_key) as conn:
        ensure_agent_event_schema(conn)
        existing = {
            str(row["event_id"])
            for row in conn.execute(
                "SELECT event_id FROM agent_field_change_events WHERE event_id IN ({})".format(
                    ",".join("?" for _ in events)
                ),
                [event["event_id"] for event in events],
            ).fetchall()
        }
    return [event for event in events if event["event_id"] not in existing]


if __name__ == "__main__":
    raise SystemExit(main())
