"""OpenCTP data-center interfaces."""
from .client import (
    fetch_markets,
    fetch_products,
    fetch_instruments,
    fetch_prices,
    fetch_times,
    frame_markets,
    frame_products,
    frame_instruments,
    frame_prices,
    frame_times,
    instruments_to_contract_specs,
)
from .fields import (
    canonical_field,
    get_product_field,
    get_product_fields,
    get_multiplier,
    get_min_tick,
    get_min_trade_quantity,
    get_long_margin_ratio,
    get_short_margin_ratio,
    get_open_ratio,
    get_open_fixed,
    get_close_ratio,
    get_close_fixed,
    get_closetoday_ratio,
    get_closetoday_fixed,
)

__all__ = [
    "fetch_markets",
    "fetch_products",
    "fetch_instruments",
    "fetch_prices",
    "fetch_times",
    "frame_markets",
    "frame_products",
    "frame_instruments",
    "frame_prices",
    "frame_times",
    "instruments_to_contract_specs",
    "canonical_field",
    "get_product_field",
    "get_product_fields",
    "get_multiplier",
    "get_min_tick",
    "get_min_trade_quantity",
    "get_long_margin_ratio",
    "get_short_margin_ratio",
    "get_open_ratio",
    "get_open_fixed",
    "get_close_ratio",
    "get_close_fixed",
    "get_closetoday_ratio",
    "get_closetoday_fixed",
]
